name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:

    env:
      RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
      RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

        with:
          node-version: 22
        
      - name: Install Dependencies
        run: npm install
      
      - name: Run Lint
        run: npm run lint
      
      - name: Build Check
        run: npm run build

      - name: Build Docker Image
        run: docker build -t ecommerce-api .
        
      - name: Run Tests
        run: npm test


